schema = 3

[mod]
  [mod."cel.dev/expr"]
    version = "v0.25.1"
    hash = "sha256-TEdMxFUPK7IZuCXMufwCkbN+ZZIXSQclljIybFZcByo="
  [mod."dario.cat/mergo"]
    version = "v1.0.2"
    hash = "sha256-p6jdiHlLEfZES8vJnDywG4aVzIe16p0CU6iglglIweA="
  [mod."github.com/antlr4-go/antlr/v4"]
    version = "v4.13.1"
    hash = "sha256-beAuxHNRUuhzcSJUh/8ztVf1zCUiaT72fg2Jvx0AuNQ="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/blang/semver/v4"]
    version = "v4.0.0"
    hash = "sha256-dJC22MjnfT5WqJ7x7Tc3Bvpw9tFnBn9HqfWFiM57JVc="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.13.0"
    hash = "sha256-lB2Z29RDLiVQE5NrsV1s2iHeQ4ciGwNj5OG1zJxwZV8="
  [mod."github.com/evanphx/json-patch"]
    version = "v5.9.11+incompatible"
    hash = "sha256-1iyZpBaeBLmNkJ3T4A9fAEXEYB9nk9V02ug4pwl5dy0="
  [mod."github.com/evanphx/json-patch/v5"]
    version = "v5.9.11"
    hash = "sha256-DaWzRi5dIr3U7kJlV3Qm1DWoKh5W+FI2BW/ATXT40J4="
  [mod."github.com/fatih/color"]
    version = "v1.18.0"
    hash = "sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.9.0"
    hash = "sha256-/IZK76MRCrz9XCiilieH5tKaLnIWyPJhwxDoVKB8dFc="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.22.4"
    hash = "sha256-V76k+oQUyqkWcpa64bOirteoCfdn1Xm9TLH0/7W4Uxc="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.21.4"
    hash = "sha256-R+Q/MOSRTMiOaZutRmjv/qwbU9/cUWN59Hwr2LgDz2U="
  [mod."github.com/go-openapi/swag"]
    version = "v0.25.4"
    hash = "sha256-aFQeLf95JC5gWLwIJXxhZHK9RxiGhh9IYV0MEYldDr4="
  [mod."github.com/go-openapi/swag/cmdutils"]
    version = "v0.25.4"
    hash = "sha256-nhlq5w/ULjwy7nptKcRryjZPlv3QG0FmgcBSOclqRlA="
  [mod."github.com/go-openapi/swag/conv"]
    version = "v0.25.4"
    hash = "sha256-uHgTdZC76LMSsq+x+RyeclnOgBsS0ID2cLgfjzFk0KQ="
  [mod."github.com/go-openapi/swag/fileutils"]
    version = "v0.25.4"
    hash = "sha256-NWacswHRvNZ81WzazA8yUmeDymtne2l8zLdArBmeYAU="
  [mod."github.com/go-openapi/swag/jsonname"]
    version = "v0.25.4"
    hash = "sha256-Z6uETeudh8W+/SGxFBnOB/VlJeRPRkFgCyJmntpz7bc="
  [mod."github.com/go-openapi/swag/jsonutils"]
    version = "v0.25.4"
    hash = "sha256-TQGeMImUuL5BWDoBHKAjZ1BvvxPXkFrV3TMgb82IrLk="
  [mod."github.com/go-openapi/swag/loading"]
    version = "v0.25.4"
    hash = "sha256-xr8OnFqB/kwBj3yf9HiLJwDcpL7I3/qJYlKb6VWbVFA="
  [mod."github.com/go-openapi/swag/mangling"]
    version = "v0.25.4"
    hash = "sha256-NrmwNgRJIUlOaAGt+XutHWSHy9e1COMnVE8B0UY5+sQ="
  [mod."github.com/go-openapi/swag/netutils"]
    version = "v0.25.4"
    hash = "sha256-wRMCQX/wIOvWm1g2UURobhzI47OldVqzlYYzwotLNTU="
  [mod."github.com/go-openapi/swag/stringutils"]
    version = "v0.25.4"
    hash = "sha256-rVo5NBH+oLLX9kaemUYWILd+TKw/TDTB8UdSz+mn3m8="
  [mod."github.com/go-openapi/swag/typeutils"]
    version = "v0.25.4"
    hash = "sha256-59RHnK6ugsAUc+A8DZCj7gZ3bJnt01Al7T/1kzM9PpA="
  [mod."github.com/go-openapi/swag/yamlutils"]
    version = "v0.25.4"
    hash = "sha256-zba7QX7Ds05oZq1opP/vwRSBEDaJ1pKm+9DgrsOuR9w="
  [mod."github.com/gobuffalo/flect"]
    version = "v1.0.3"
    hash = "sha256-gpA1fe9XTjZ9r+yYCysCgXKo1AmYNuNFwWn7ZQ4Ky1M="
  [mod."github.com/google/btree"]
    version = "v1.1.3"
    hash = "sha256-/6Us2eNRFi2IIp7p5uPUXLridilAdk4SmZhcTYR0csw="
  [mod."github.com/google/cel-go"]
    version = "v0.26.1"
    hash = "sha256-XVL+pNGjmLrQefpB7qj419zWl1qhPVHmVxsP/Ro1AtE="
  [mod."github.com/google/gnostic-models"]
    version = "v0.7.1"
    hash = "sha256-dfSFaYzgD4HrdL6ZsN8V9w0SMzx0WXl38dIy4dnjhhc="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.27.4"
    hash = "sha256-FSrLVW0wd3E5yQH5OOQBitILOiOjdl8jig7yj7JO+8s="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.14"
    hash = "sha256-JC60PjKj7MvhZmUHTZ9p372FV72I9Mxvli3fivTbxuA="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.3-0.20250322232337-35a7c28c31ee"
    hash = "sha256-0pkWWZRB3lGFyzmlxxrm0KWVQo9HNXNafaUu3k+rE1g="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.23.2"
    hash = "sha256-3GD4fBFa1tJu8MS4TNP6r2re2eViUE+kWUaieIOQXCg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.2"
    hash = "sha256-q6Fh6v8iNJN9ypD47LjWmx66YITa3FyRjZMRsuRTFeQ="
  [mod."github.com/prometheus/common"]
    version = "v0.67.5"
    hash = "sha256-pDzmYsAANsaIf3W9HxpbgRnZ4BkPhJBBwzKq2E58FRw="
  [mod."github.com/prometheus/procfs"]
    version = "v0.19.2"
    hash = "sha256-PJW21pew9v+XA7Miow8JVPct+FPIHmQHphwO+g2kNWA="
  [mod."github.com/spf13/afero"]
    version = "v1.15.0"
    hash = "sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.3.1"
    hash = "sha256-yptboRvbZtX+OEdlTgJnrCT+bvaMgCJp5B9ifEaSfw0="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.64.0"
    hash = "sha256-xilqHTTNmvhxDFfTnE8ZytsrYq5gYFD77/glakljCy0="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.40.0"
    hash = "sha256-Cu9ZCLMAd9kGsmpnvoyqwm0IkF4Uk6Xo+8OsP9l+wUQ="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.39.0"
    hash = "sha256-7pfSAaoIS1fbtVd9CCx6J4/DHBsmReon6r9Hocb2CCU="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.39.0"
    hash = "sha256-UkdZZhcFh+JcHzeUGmvGXqM2wmj17HHaXkjw/+vpbzg="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.40.0"
    hash = "sha256-oPA3DfQ5vXhlVkBPksu/kKYBSrssefq4vtnd4vm9K8w="
  [mod."go.uber.org/zap"]
    version = "v1.27.1"
    hash = "sha256-bn/MMu7X3GkUuW12Xwn9JYbOJeEu9+yoQtkmO+36xlQ="
  [mod."go.yaml.in/yaml/v2"]
    version = "v2.4.3"
    hash = "sha256-WqfrOUQFvfuORgl1yyVOcsEXU/vwWQHkcVWx3vCxvaw="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20260112195511-716be5621a96"
    hash = "sha256-rWqwXzLvvhcI/ZkOQMqCXMKI5FAuHd9YNoKTXujmboA="
  [mod."golang.org/x/mod"]
    version = "v0.32.0"
    hash = "sha256-4gbgIqTOo0vcYV3l4MIwmT/h8H9PXmcfrJ3z4B26Zl0="
  [mod."golang.org/x/net"]
    version = "v0.49.0"
    hash = "sha256-arK6PWwO9tQUJVb57QXUEXfgcB6ISI6qjVB0eC4zcnw="
  [mod."golang.org/x/oauth2"]
    version = "v0.34.0"
    hash = "sha256-5eqpGGxJ7FJsPmfRek6roeGmkWHBMJaWYXyz8gXJsS4="
  [mod."golang.org/x/sync"]
    version = "v0.19.0"
    hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno="
  [mod."golang.org/x/sys"]
    version = "v0.40.0"
    hash = "sha256-KDe+wMr7dfMFwKMJEljzk+f82pQWFFPoFHivjD7qJGg="
  [mod."golang.org/x/term"]
    version = "v0.39.0"
    hash = "sha256-diP4VknZDlJmhGQdcsXwI2+sFayQdsILFuxK1FBPaUE="
  [mod."golang.org/x/text"]
    version = "v0.33.0"
    hash = "sha256-XdA6D39ESuJkaaM/SRBnqZzjKUwi6Gbt1Si1nvauTr4="
  [mod."golang.org/x/time"]
    version = "v0.14.0"
    hash = "sha256-fVjpq0ieUHVEOTSElDVleMWvfdcqojZchqdUXiC7NnY="
  [mod."golang.org/x/tools"]
    version = "v0.41.0"
    hash = "sha256-/Plnksa1jSr4jYJc2oCH9fcjGbWocM7EYposMP0tScQ="
  [mod."gomodules.xyz/jsonpatch/v2"]
    version = "v2.5.0"
    hash = "sha256-L3Xy24GTtcDHmMgc9rlgUm3GrxFO7XQKJhfYIr3li1s="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20260114163908-3f89685c29c3"
    hash = "sha256-X842u0vFs4rOKEX7anzjTAo6r6Rgavf9XBaG7ZjuwpY="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20260203192932-546029d2fa20"
    hash = "sha256-gdgUw1LzgVOrarF1cGBUI9uoaR/d6lur2RwxUDKnOZA="
  [mod."google.golang.org/grpc"]
    version = "v1.78.0"
    hash = "sha256-oKsu3+Eae5tpFOZ9K2ZzYh1FgdYdEnEIB1C+UIxSD+E="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.11"
    hash = "sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE="
  [mod."gopkg.in/evanphx/json-patch.v4"]
    version = "v4.13.0"
    hash = "sha256-1iyZpBaeBLmNkJ3T4A9fAEXEYB9nk9V02ug4pwl5dy0="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."k8s.io/api"]
    version = "v0.35.0"
    hash = "sha256-eIie0MFXkmNsfiO58pg+ThJ1wPcYh3T7Gch9p2GrT64="
  [mod."k8s.io/apiextensions-apiserver"]
    version = "v0.35.0"
    hash = "sha256-RZdGkV4SoCTY022pIzQbeVwaxIYhIpXapLZrD593gh8="
  [mod."k8s.io/apimachinery"]
    version = "v0.35.0"
    hash = "sha256-+dplbHUOfaCaD2E9IS4F3lnjSCr/a4LjTgdB9de92Pw="
  [mod."k8s.io/client-go"]
    version = "v0.35.0"
    hash = "sha256-s+o7ybLe83chueBIVvYRibI2HCk+QQoWTjfXqmzsjHs="
  [mod."k8s.io/code-generator"]
    version = "v0.35.0"
    hash = "sha256-0F8vNVdF/quBPGxOpxBL/GhupnkMoTE8dcZYX57RZKk="
  [mod."k8s.io/component-base"]
    version = "v0.35.0"
    hash = "sha256-fIAmKs3/T8oHrXBX3sMWr/D1DGhyCsgM+6ZFdaA8BXU="
  [mod."k8s.io/gengo/v2"]
    version = "v2.0.0-20251215205346-5ee0d033ba5b"
    hash = "sha256-FxD4b+cOzKuXsGI4NpsaUK/YTOMxugMGAh2jY3od3p8="
  [mod."k8s.io/klog/v2"]
    version = "v2.130.1"
    hash = "sha256-n5vls1o1a0V0KYv+3SULq4q3R2Is15K8iDHhFlsSH4o="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20260127142750-a19766b6e2d4"
    hash = "sha256-NS8NvGTX3Ycoc4JU/jwLgtNlD5OOQ5zk2hzvFFSD/jM="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20260108192941-914a6e750570"
    hash = "sha256-eFcd1fZT9M7wc/foeEAUj3jgHJfEY9U3lVqQTkIVJ44="
  [mod."sigs.k8s.io/apiserver-network-proxy/konnectivity-client"]
    version = "v0.34.0"
    hash = "sha256-98ScvhhmVxEVAGv9rhk10ceYUadNOuBERtCcdaIb42s="
  [mod."sigs.k8s.io/controller-runtime"]
    version = "v0.23.1"
    hash = "sha256-iOaYAJgy/Q1Hi6afs5mLtP8K5J8Cs/MlDoGp8wE1GOY="
  [mod."sigs.k8s.io/controller-tools"]
    version = "v0.20.0"
    hash = "sha256-1/v8hCCykTDMjhx4jM84/v+WJlQ8M1whdgpGfgmSRRU="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20250730193827-2d320260d730"
    hash = "sha256-y3vUPJYL6oxu/8c0j4vgX6fzqHtVPSCjfyuWkZYf6+I="
  [mod."sigs.k8s.io/randfill"]
    version = "v1.0.0"
    hash = "sha256-xldQxDwW84hmlihdSOFfjXyauhxEWV9KmIDLZMTcYNo="
  [mod."sigs.k8s.io/structured-merge-diff/v6"]
    version = "v6.3.2-0.20260122202528-d9cc6641c482"
    hash = "sha256-4ZUkeHKvdhsZmFSSZKAL/1GZdPO6735BY6FqRc+8tog="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.6.0"
    hash = "sha256-49hg7IVPzwxeovp+HTMiWa/10NMMTSTjAdCmIv6p9dw="
